[workspace]

members = [
    "treeedb",
    "treeedb-c",
    "treeedb-cpp",
    "treeedb-csharp",
    "treeedb-java",
    "treeedb-javascript",
    "treeedb-rust",
    "treeedb-souffle",
    "treeedb-php",
    "treeedb-rust",
    "treeedb-swift",
    "treeedbgen",
    "treeedbgen-souffle",
    "treeedbgen-souffle-c",
    "treeedbgen-souffle-cpp",
    "treeedbgen-souffle-csharp",
    "treeedbgen-souffle-java",
    "treeedbgen-souffle-javascript",
    "treeedbgen-souffle-php",
    "treeedbgen-souffle-rust",
    "treeedbgen-souffle-souffle",
    "treeedbgen-souffle-swift",
]

[profile.release]
lto = "thin"
