[package]
name = "treeedb-java"
version = "0.2.0-rc.1"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generate Datalog facts from Java source code"
keywords = ["datalog", "java", "parsing", "souffle"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
treeedb = { version = "0.2.0-rc.1", path = "../treeedb", features = ["cli"] }
tree-sitter-java = { version = "0.23" }
