[package]
name = "treeedbgen"
version = "0.2.0-rc.1"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Parse node-types.json from a tree-sitter grammar"
keywords = ["parsing", "tree-sitter"]

[lints]
workspace = true

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = []
cli = ["dep:clap"]
