[package]
name = "treeedbgen-souffle"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generate Souffl√© types and relations from tree-sitter grammars"
keywords = ["datalog", "parsing", "souffle"]

[lints]
workspace = true

[dependencies]
anyhow = { version = "1", optional = true }
clap = { version = "4", features = ["derive"], optional = true }
heck = "0.5"
thiserror = "2"
treeedbgen = { path = "../treeedbgen", version = "0.1.0" }
serde_json = "1"

[features]
default = []
cli = ["dep:anyhow", "dep:clap"]
