[package]
name = "treeedb-go"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generate Datalog facts from Go source code"
keywords = ["datalog", "go", "parsing", "souffle"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
treeedb = { version = "0.1.0", path = "../treeedb", features = ["cli"] }
tree-sitter-go = { version = "0.25" }
