[package]
name = "treeedbgen-souffle"
version = "0.1.0"
edition = "2021"
description = "Generate Souffl√© types and relations from tree-sitter grammars"
keywords = ["datalog", "parsing", "souffle"]
authors = ["Langston Barrett <langston.barrett@gmail.com>"]
license = "MIT"
readme = "../README.md"
homepage = "https://github.com/langston-barrett/treeedb"
repository = "https://github.com/langston-barrett/treeedb"

[lints]
workspace = true

[dependencies]
anyhow = { version = "1", optional = true }
clap = { version = "4", features = ["derive"], optional = true }
heck = "0.5"
thiserror = "2"
treeedbgen = { path = "../treeedbgen", version = "0.1.0" }
serde_json = "1"

[features]
default = []
cli = ["dep:anyhow", "dep:clap"]
