[package]
name = "treeedbgen-souffle-perl"
version = "0.2.0-rc.1"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generate Souffl√© types and relations from the Perl tree-sitter grammar"
keywords = ["datalog", "perl", "parsing", "souffle"]

[lints]
workspace = true

[dependencies]
anyhow = "1"
treeedbgen-souffle = { version = "0.2.0-rc.1", path = "../treeedbgen-souffle", features = ["cli"] }
tree-sitter-perl = { git = "https://github.com/tree-sitter-perl/tree-sitter-perl", branch = "release" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3"
