[package]
name = "treeedbgen-souffle-csharp"
version = "0.2.0-rc.1"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generate Souffl√© types and relations from the C# tree-sitter grammar"
keywords = ["datalog", "csharp", "parsing", "souffle"]

[lints]
workspace = true

[dependencies]
anyhow = "1"
treeedbgen-souffle = { version = "0.2.0-rc.1", path = "../treeedbgen-souffle", features = ["cli"] }
tree-sitter-c-sharp = { version = "0.23", git = "https://github.com/tree-sitter/tree-sitter-c-sharp" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3"
