[package]
name = "treeedb-souffle"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generate Datalog facts from Souffl√© source code"
keywords = ["datalog", "parsing", "souffle"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
treeedb = { version = "0.1.0", path = "../treeedb", features = ["cli"] }
tree-sitter-souffle = { version = "0.5.0" }
